from lag.envs.jsbsim.tasks.heading_task import HeadingTask
from lag.envs.jsbsim.tasks.singlecombat_task import SingleCombatTask, HierarchicalSingleCombatTask
from lag.envs.jsbsim.tasks.singlecombat_with_missle_task import SingleCombatDodgeMissileTask, HierarchicalSingleCombatDodgeMissileTask, HierarchicalSingleCombatShootTask, SingleCombatShootMissileTask