from .heading_task import HeadingTask, HeadingContinuousTask, HeadingAndAltitudeTask
from .singlecombat_task import SingleCombatTask
from .singlecombat_with_missle_task import SingleCombatWithMissileTask
from .singlecombat_with_artillery_task import SingleCombatWithArtilleryTask
from .multiplecombat_task import MultipleCombatTask